import {createHash} from 'node:crypto';
import {mkdir, copyFile, cp, rm, readFile, writeFile} from 'node:fs/promises';
const root = new URL('../', import.meta.url);
const output = new URL('dist/', root);
await rm(output, {recursive:true, force:true});
await mkdir(output, {recursive:true});
for (const name of ['index.html','styles.css','app.js','player.js','storage.js','media.js','pwa.js','manifest.webmanifest','sw.js','test-video.mp4','THIRD_PARTY_NOTICES.md']) await copyFile(new URL(name,root),new URL(name,output));
await cp(new URL('icons/',root),new URL('icons/',output),{recursive:true});
await cp(new URL('licenses/',root),new URL('licenses/',output),{recursive:true});
await mkdir(new URL('vendor/',output),{recursive:true});
await cp(new URL('node_modules/@ffmpeg/ffmpeg/dist/esm/',root),new URL('vendor/ffmpeg/',output),{recursive:true});
await cp(new URL('node_modules/@ffmpeg/core/dist/esm/',root),new URL('vendor/core/',output),{recursive:true});
await copyFile(new URL('node_modules/@ffmpeg/ffmpeg/package.json',root),new URL('vendor/ffmpeg-package.json',output));
await copyFile(new URL('node_modules/@ffmpeg/core/package.json',root),new URL('vendor/core-package.json',output));
await copyFile(new URL('.nojekyll',root),new URL('.nojekyll',output));
console.log('DojoFlow prêt dans dist/');
const hash=createHash('sha256');
for(const file of ['index.html','styles.css','app.js','player.js','storage.js','media.js','pwa.js','sw.js','manifest.webmanifest','package-lock.json','test-video.mp4','icons/icon.svg','icons/icon-192.png','icons/icon-512.png','icons/apple-touch-icon.png','THIRD_PARTY_NOTICES.md'])hash.update(await readFile(new URL(file,root)));
await writeFile(new URL('sw.js',output),(await readFile(new URL('sw.js',root),'utf8')).replace('__BUILD_ID__',hash.digest('hex').slice(0,16)));
